baseURL = "https://nnkken.github.io/"
languageCode = "zh-tw"
title = "Chung's Notebook"
theme = "ezhil"

# Chroma Syntax Highlighting
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"

[params]
    author = "Chung Wu"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/post"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Github"
url = "https://github.com/nnkken"
weight = 4